#!/usr/bin/env python3
"""Emit golden wire-compat fixtures from the REAL Token Vault contract.

This imports the authoritative signing code from the TV backend — not a
re-implementation — so the fixtures prove byte-for-byte parity:

  * compute_hmac_signature  (backend/webhook/client.py)
  * _sign_ticket            (backend/webhook/credential_tickets.py)

Usage:
    TV_BACKEND=/path/to/tokenvault/backend python3 gen_fixtures.py > fixtures.json

The fixtures use a fixed timestamp and a far-future ticket expiry so the vitest
suite is clock-independent (it exercises the pure verifiers, not the time
window). Regenerate and commit whenever the TV signing contract changes.
"""

import base64
import json
import os
import sys

_DEFAULT_BACKEND = "/home/cgrant/tokenvault/backend"
sys.path.insert(0, os.environ.get("TV_BACKEND", _DEFAULT_BACKEND))

from webhook.client import compute_hmac_signature  # noqa: E402
from webhook.credential_tickets import _sign_ticket  # noqa: E402

# Deterministic, obviously-fake key material (never a real secret).
HMAC_SECRET = bytes(range(32))
WRONG_SECRET = bytes((b + 1) % 256 for b in range(32))

# ── Request HMAC golden vector ────────────────────────────────────────────────
# Mirror how client.call_webhook builds the signed payload: fold requestId into
# the body, serialize compact, then sign "{timestamp}.{body}".
TIMESTAMP = "1700000000"
request_body = {"operation": "get", "collection": "tokens", "key": "github"}
request_body["requestId"] = "req_testfixture01"
request_body_json = json.dumps(request_body, separators=(",", ":"))
request_signature = compute_hmac_signature(HMAC_SECRET, TIMESTAMP, request_body_json)

# ── Ticket golden vector ──────────────────────────────────────────────────────
ticket_payload = {
    "sub": "user_test",
    "svc": "github",
    "pur": "agent_credential",
    "iat": 1700000000,
    "exp": 9999999999,  # far future → clock-independent
    "nonce": "deadbeefdeadbeefdeadbeefdeadbeef",
    "aid": "agent_test",
}
ticket_value = _sign_ticket(HMAC_SECRET, ticket_payload)

fixtures = {
    "_note": "Generated by gen_fixtures.py from the real TV backend contract.",
    "hmacSecretB64": base64.b64encode(HMAC_SECRET).decode(),
    "wrongSecretB64": base64.b64encode(WRONG_SECRET).decode(),
    "request": {
        "timestamp": TIMESTAMP,
        "bodyJson": request_body_json,
        "signature": request_signature,
    },
    "ticket": {
        "value": ticket_value,
        "payload": ticket_payload,
    },
}

print(json.dumps(fixtures, indent=2))
