// Wire-compat gate: our verifiers must accept signatures + tickets produced by
// the REAL Token Vault backend (golden vectors in fixtures.json, generated by
// gen_fixtures.py) and reject the wrong-key / replay cases.

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { base64Decode, utf8 } from "../../src/core/crypto/encoding.ts";
import { computeRequestSignature, verifyRequestSignature } from "../../src/core/protocol/hmac.ts";
import { verifyTicket } from "../../src/core/protocol/tickets.ts";
import { MemoryReplayGuard } from "../../src/adapters/replay/memory.ts";

interface Fixtures {
  hmacSecretB64: string;
  wrongSecretB64: string;
  request: { timestamp: string; bodyJson: string; signature: string };
  ticket: { value: string; payload: Record<string, unknown> };
}

const fx: Fixtures = JSON.parse(
  readFileSync(new URL("./fixtures.json", import.meta.url), "utf-8"),
);

const secret = base64Decode(fx.hmacSecretB64);
const wrongSecret = base64Decode(fx.wrongSecretB64);

describe("request HMAC (client.py compute_hmac_signature)", () => {
  it("recomputes the exact golden signature over the raw bytes", async () => {
    const sig = await computeRequestSignature(secret, fx.request.timestamp, utf8(fx.request.bodyJson));
    expect(sig).toBe(fx.request.signature);
  });

  it("accepts the golden signature", async () => {
    const ok = await verifyRequestSignature(
      secret,
      fx.request.timestamp,
      utf8(fx.request.bodyJson),
      fx.request.signature,
    );
    expect(ok).toBe(true);
  });

  it("rejects the golden signature under the wrong key", async () => {
    const ok = await verifyRequestSignature(
      wrongSecret,
      fx.request.timestamp,
      utf8(fx.request.bodyJson),
      fx.request.signature,
    );
    expect(ok).toBe(false);
  });
});

describe("credential ticket (credential_tickets.py _sign_ticket)", () => {
  it("accepts a real TV-signed ticket and decodes its payload", async () => {
    const payload = await verifyTicket(fx.ticket.value, secret, new MemoryReplayGuard());
    expect(payload).toMatchObject(fx.ticket.payload);
  });

  it("rejects a ticket verified under the wrong key", async () => {
    await expect(
      verifyTicket(fx.ticket.value, wrongSecret, new MemoryReplayGuard()),
    ).rejects.toThrow();
  });

  it("rejects a replayed nonce", async () => {
    const guard = new MemoryReplayGuard();
    await verifyTicket(fx.ticket.value, secret, guard); // first use OK
    await expect(verifyTicket(fx.ticket.value, secret, guard)).rejects.toThrow();
  });
});
