package webhook

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// DefaultImage is the published webhook image the generated Compose references.
// Override with `tvault webhook init --image`.
const DefaultImage = "ghcr.io/c-lgrant/tvault-webhook:latest"

// webhookEntrypoint runs the webhook as a plain HTTP service, bypassing the
// image's bundled-ngrok entrypoint so the tunnel can live in its own container.
var webhookEntrypoint = []string{
	"gunicorn", "-k", "uvicorn.workers.UvicornWorker",
	"--bind", "0.0.0.0:8080", "main:app",
}

type composeFile struct {
	Services map[string]composeService `yaml:"services"`
	Volumes  map[string]struct{}       `yaml:"volumes,omitempty"`
}

type composeService struct {
	Image       string            `yaml:"image,omitempty"`
	Entrypoint  []string          `yaml:"entrypoint,omitempty"`
	Command     []string          `yaml:"command,omitempty"`
	Environment map[string]string `yaml:"environment,omitempty"`
	Volumes     []string          `yaml:"volumes,omitempty"`
	NetworkMode string            `yaml:"network_mode,omitempty"`
	Hostname    string            `yaml:"hostname,omitempty"`
}

// externalURL returns the public webhook URL for a method given the collected
// param values. ngrok derives it from NGROK_URL; every other method collects
// WEBHOOK_EXTERNAL_URL directly.
func externalURL(m Method, values map[string]string) string {
	if m.ID == "ngrok" {
		host := strings.TrimPrefix(values["NGROK_URL"], "https://")
		return "https://" + host
	}
	return values["WEBHOOK_EXTERNAL_URL"]
}

// buildCompose returns the docker-compose.yml bytes for a method.
func buildCompose(m Method, image string) ([]byte, error) {
	webhook := composeService{
		Image:       image,
		Entrypoint:  webhookEntrypoint,
		Environment: map[string]string{"WEBHOOK_EXTERNAL_URL": "${WEBHOOK_EXTERNAL_URL}"},
		Volumes:     []string{"tv-webhook-data:/data"},
	}
	cf := composeFile{
		Services: map[string]composeService{},
		Volumes:  map[string]struct{}{"tv-webhook-data": {}},
	}

	switch m.ID {
	case "ngrok":
		cf.Services["webhook"] = webhook
		cf.Services["tunnel"] = composeService{
			Image:       "ngrok/ngrok:latest",
			Command:     []string{"http", "webhook:8080", "--url=${NGROK_URL}"},
			Environment: map[string]string{"NGROK_AUTHTOKEN": "${NGROK_AUTHTOKEN}"},
		}
	case "cloudflare":
		cf.Services["webhook"] = webhook
		cf.Services["tunnel"] = composeService{
			Image:   "cloudflare/cloudflared:latest",
			Command: []string{"tunnel", "--no-autoupdate", "run", "--token", "${CLOUDFLARE_TUNNEL_TOKEN}"},
		}
	case "tailscale":
		webhook.NetworkMode = "service:tailscale"
		cf.Services["tailscale"] = composeService{
			Image:    "tailscale/tailscale:latest",
			Hostname: "${TS_HOSTNAME}",
			Environment: map[string]string{
				"TS_AUTHKEY":      "${TS_AUTHKEY}",
				"TS_USERSPACE":    "true",
				"TS_STATE_DIR":    "/var/lib/tailscale",
				"TS_SERVE_CONFIG": "/config/serve.json",
			},
			Volumes: []string{"tailscale-state:/var/lib/tailscale", "./serve.json:/config/serve.json"},
		}
		cf.Services["webhook"] = webhook
		cf.Volumes["tailscale-state"] = struct{}{}
	case "custom":
		cf.Services["webhook"] = webhook
	default:
		return nil, fmt.Errorf("unknown method %q", m.ID)
	}

	var b strings.Builder
	b.WriteString("# Token Vault webhook — generated by `tvault webhook init`\n")
	b.WriteString("# Docs: https://docs.tokenvault.uk/guides/webhook-setup\n")
	b.WriteString("# Edit freely; re-run `tvault webhook init` to regenerate.\n")
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(cf); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return []byte(b.String()), nil
}

// serveJSON is the Tailscale Funnel config: expose :443 publicly, proxy to the
// webhook on localhost:8080. ${TS_CERT_DOMAIN} is substituted by tailscaled.
const serveJSON = `{
  "TCP": { "443": { "HTTPS": true } },
  "Web": {
    "${TS_CERT_DOMAIN}:443": {
      "Handlers": { "/": { "Proxy": "http://127.0.0.1:8080" } }
    }
  },
  "AllowFunnel": { "${TS_CERT_DOMAIN}:443": true }
}
`

// GeneratedFile is one file the generator writes into the project directory.
type GeneratedFile struct {
	Name string
	Mode os.FileMode
	Data []byte
}

// buildEnv returns the .env bytes: every collected value plus the resolved
// WEBHOOK_EXTERNAL_URL, sorted by key for deterministic output.
func buildEnv(m Method, values map[string]string) []byte {
	out := map[string]string{}
	for k, v := range values {
		out[k] = v
	}
	out["WEBHOOK_EXTERNAL_URL"] = externalURL(m, values)
	keys := make([]string, 0, len(out))
	for k := range out {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("# Token Vault webhook env — generated by `tvault webhook init`\n")
	b.WriteString("# Contains tunnel-provider secrets. Do not commit (see .gitignore).\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s=%s\n", k, out[k])
	}
	return []byte(b.String())
}

// buildREADME returns a short project README with next steps and doc links.
func buildREADME(m Method) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "# Token Vault webhook (%s)\n\n", m.Label)
	b.WriteString("Generated by `tvault webhook init`.\n\n")
	b.WriteString("## Next steps\n\n")
	b.WriteString("1. `tvault webhook up`     — start the webhook + tunnel\n")
	b.WriteString("2. `tvault webhook bind`   — connect it to your vault (no browser)\n")
	b.WriteString("3. `tvault webhook status` — check local + backend state\n\n")
	b.WriteString("## Docs\n\n")
	b.WriteString("- Webhook setup guide: https://docs.tokenvault.uk/guides/webhook-setup\n")
	b.WriteString("- Webhook protocol:    https://docs.tokenvault.uk/webhook-protocol\n")
	fmt.Fprintf(&b, "- %s setup:\t%s\n", m.Label, m.HelpURL)
	return []byte(b.String())
}

// Generate builds the full file set for a method. image overrides the webhook
// image when non-empty.
func Generate(m Method, values map[string]string, image string) ([]GeneratedFile, error) {
	if image == "" {
		image = DefaultImage
	}
	compose, err := buildCompose(m, image)
	if err != nil {
		return nil, err
	}
	files := []GeneratedFile{
		{Name: "docker-compose.yml", Mode: 0o644, Data: compose},
		{Name: ".env", Mode: 0o600, Data: buildEnv(m, values)},
		{Name: "README.md", Mode: 0o644, Data: buildREADME(m)},
		{Name: ".gitignore", Mode: 0o644, Data: []byte(".env\n")},
	}
	if m.ID == "tailscale" {
		files = append(files, GeneratedFile{Name: "serve.json", Mode: 0o644, Data: []byte(serveJSON)})
	}
	return files, nil
}

// WriteProject writes the generated files into dir, creating it if needed. It
// refuses to overwrite an existing docker-compose.yml unless force is true.
func WriteProject(dir string, files []GeneratedFile, force bool) error {
	if !force {
		if _, err := os.Stat(filepath.Join(dir, "docker-compose.yml")); err == nil {
			return fmt.Errorf("%s already contains a docker-compose.yml — pass --force to overwrite", dir)
		}
	} else {
		if _, err := os.Stat(filepath.Join(dir, ".env")); err == nil {
			fmt.Fprintf(os.Stderr, "warning: overwriting existing %s/.env — any hand-edited secrets will be lost\n", dir)
		}
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	for _, f := range files {
		path := filepath.Join(dir, f.Name)
		if err := os.WriteFile(path, f.Data, f.Mode); err != nil {
			return err
		}
		// os.WriteFile does not chmod an existing file; enforce the mode so a
		// regenerated .env can never be left world-readable.
		if err := os.Chmod(path, f.Mode); err != nil {
			return err
		}
	}
	return nil
}
